### ISSUE TITLE
The remove duplicate nodes option is now causing a SAXParseException.

### ISSUE THREAD

**Issue by wdschei** [rackerlabs/api-checker#376]
When executing the command:
```
java -jar wadltest-2.5.0-jar-with-dependencies.jar -dpr simple-rbac.wadl
```
with the WADL file containing:
```
<application xmlns:rax="http://docs.rackspace.com/api"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema"
         xmlns="http://wadl.dev.java.net/2009/02"
    >
  <resources base="http://localhost">
    <resource id="_0be44e11-68e6-44d4-acae-ec6a366282ba" path="/path/to/this">
      <method name="GET"    id="_0be44e11-68e6-44d4-acae-ec6a366282ba-GET"    rax:roles="role1 role2 role3 role4"/>
    </resource>
    <resource id="_0e126d22-d8d2-4ece-8667-b19875ae1e12" path="/path/to/this">
      <method name="PUT"    id="_0e126d22-d8d2-4ece-8667-b19875ae1e12-PUT"    rax:roles="role1 role2 role3"/>
    </resource>
    <resource id="_b3d2229d-cc90-4d53-9f05-c1c60117af07" path="/path/to/this">
      <method name="POST"   id="_b3d2229d-cc90-4d53-9f05-c1c60117af07-POST"   rax:roles="role1 role2"/>
    </resource>
    <resource id="_4724d9ab-d560-4668-bc18-3690cc7faa76" path="/path/to/this">
      <method name="DELETE" id="_4724d9ab-d560-4668-bc18-3690cc7faa76-DELETE" rax:roles="role1"/>
    </resource>
    <resource id="_bed37f49-c275-474b-8681-a3a48918ddb9" path="/path/to/that">
      <method name="GET"    id="_bed37f49-c275-474b-8681-a3a48918ddb9-GET"    />
      <method name="PUT"    id="_bed37f49-c275-474b-8681-a3a48918ddb9-PUT"    />
    </resource>
    <resource id="_6fdeaf12-ca1d-443e-bd77-25c5cb8b0284" path="/path/to/that">
      <method name="GET"    id="_6fdeaf12-ca1d-443e-bd77-25c5cb8b0284-GET"    rax:roles="role1"/>
      <method name="PUT"    id="_6fdeaf12-ca1d-443e-bd77-25c5cb8b0284-PUT"    rax:roles="role1"/>
      <method name="POST"   id="_6fdeaf12-ca1d-443e-bd77-25c5cb8b0284-POST"   rax:roles="role1"/>
      <method name="DELETE" id="_6fdeaf12-ca1d-443e-bd77-25c5cb8b0284-DELETE" rax:roles="role1"/>
    </resource>
  </resources>
</application>
```
the following exception is received:
```
Loading file:/path/to/file/simple-rbac.wadl...

[ERROR] [main] org.xml.sax.SAXParseException; systemId: jar:file:/path/to/jar/wadltest-2.5.0-jar-with-dependencies.jar!/xsl/adjust-next-cont-error.xsl; cvc-id.1: There is no ID/IDREF binding for IDREF 'd43e25'.
Exception in thread "main" com.rackspace.com.papi.components.checker.wadl.WADLException: WADL Processing Error: org.xml.sax.SAXParseException; systemId: jar:file:/path/to/jar/wadltest-2.5.0-jar-with-dependencies.jar!/xsl/adjust-next-cont-error.xsl; cvc-id.1: There is no ID/IDREF binding for IDREF 'd43e25'.
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder.buildFromWADL(WADLCheckerBuilder.scala:707)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder.build(WADLCheckerBuilder.scala:766)
        at com.rackspace.com.papi.components.checker.wadl.StepBuilder.build(StepBuilder.scala:59)
        at com.rackspace.com.papi.components.checker.Validator$.apply(Validator.scala:67)
        at com.rackspace.com.papi.components.checker.cli.WadlTest$.runServer(WadlTest.scala:210)
        at com.rackspace.com.papi.components.checker.cli.WadlTest$.main(WadlTest.scala:323)
        at com.rackspace.com.papi.components.checker.cli.WadlTest.main(WadlTest.scala)
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: jar:file:/path/to/jar/wadltest-2.5.0-jar-with-dependencies.jar!/xsl/adjust-next-cont-error.xsl; cvc-id.1: There is no ID/IDREF binding for IDREF 'd43e25'.
        at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(ContentHandlerProxy.java:555)
        at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:416)
        at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:228)
        at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:576)
        at net.sf.saxon.event.ProxyReceiver.endElement(ProxyReceiver.java:182)
        at net.sf.saxon.tree.tiny.TinyElementImpl.copy(TinyElementImpl.java:414)
        at net.sf.saxon.tree.tiny.TinyDocumentImpl.copy(TinyDocumentImpl.java:287)
        at net.sf.saxon.event.Sender.sendDocumentInfo(Sender.java:243)
        at net.sf.saxon.event.Sender.send(Sender.java:126)
        at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:374)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder.com$rackspace$com$papi$components$checker$wadl$WADLCheckerBuilder$$validateChecker(WADLCheckerBuilder.scala:606)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder$$anonfun$buildFromWADL$1$$anonfun$14.apply(WADLCheckerBuilder.scala:697)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder$$anonfun$buildFromWADL$1$$anonfun$14.apply(WADLCheckerBuilder.scala:697)
        at com.rackspace.com.papi.components.checker.wadl.BuilderHelper$.applyBuildSteps(BuilderHelper.scala:129)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder$$anonfun$buildFromWADL$1.apply$mcV$sp(WADLCheckerBuilder.scala:702)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder$$anonfun$buildFromWADL$1.apply(WADLCheckerBuilder.scala:661)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder$$anonfun$buildFromWADL$1.apply(WADLCheckerBuilder.scala:661)
        at com.rackspace.cloud.api.wadl.util.XSLErrorDispatcher$class.handleXSLException(xsl-error-dispatcher.scala:15)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder.handleXSLException(WADLCheckerBuilder.scala:223)
        at com.rackspace.com.papi.components.checker.wadl.WADLCheckerBuilder.buildFromWADL(WADLCheckerBuilder.scala:661)
        ... 6 more
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/path/to/jar/wadltest-2.5.0-jar-with-dependencies.jar!/xsl/adjust-next-cont-error.xsl; cvc-id.1: There is no ID/IDREF binding for IDREF 'd43e25'.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:196)
        at org.apache.xerces.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:132)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:394)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:282)
        at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:525)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:4101)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2812)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:968)
        at org.apache.xerces.jaxp.validation.ValidatorHandlerImpl.endElement(ValidatorHandlerImpl.java:608)
        at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:414)
```

**Comment by RackerWilliams** [comment]
What seems to be triggering the issue is that you have:

`GET  /path/to/that` with no roles
`GET  /path/to/that`  with `role1`

and 

`PUT  /path/to/that` with no roles
`PUT  /path/to/that`  with `role1`

It's the fact that you have the same path with and without roles that confuses the remove dups optimization.  Should note, that without the optimization the notation is interpreted correctly with and without rax roles mask.

**Comment by wdschei** [comment]
That WADL is being auto generated from the Simple RBAC filters configuration of:
```
/path/to/this  GET       role1,role2,role3,role4
/path/to/this  PUT       role1,role2,role3
/path/to/this  POST      role1,role2
/path/to/this  DELETE    role1
/path/to/that  GET,PUT   ANY
/path/to/that  ALL       role1
/path/to/file  BAD
```
This is basically stating the `/path/to/that` is open to `ANY`one with the HTTP methods of `GET` and `PUT`, but is limited to all others by the role `role1`.

The way the DSL is converted into a WADL may need to be reevaluated.

**Comment by RackerWilliams** [comment]
You can totally describe that in a different way in WADL where it wouldn't result in the bug. (By using the `#any` role, for example.  In fact, if you use `#any` you'll get slightly more efficient machines in the current code.)  That said, the WADL you're creating is legit and it should work -- this is definitely a bug in api-checker.

**Comment by RackerWilliams** [comment]
Okay, here's the issue:

When optimizations were rewritten in 2.4.0 the order of operations were rewritten incorrectly.

In remove dups optimization which is responsible for replacing exact states with a single state, we do the following:

1. Identify steps that can be combined into 1, and select a state a "winning" step to reference.
2. Prune steps that are not connected to the start step
3. Replace references to duplicate steps with the winning step.

The result of this order is that in some cases we could reference steps that would be pruned in the next iteration.  Luckily, the procedure for selecting the winning step was very stable, so the likely hood of selecting a step that would be prune did not hit often, even in complicated scenarios.

The simple scenario above, however does cause us to select a pruned step, which is why we end up with a checker that references a missing step.  Validation of the machine catches the issue and throws the exception.

The fix is to change the order of operations:

1. Identify steps that can be combined into 1 and select a state a "winning" step to reference.
2. Replace references to duplicate steps with the winning step.
3. Prune steps that are not connected to the start step

This ensures the winning step is never pruned because it is always connected.
